name: LIG_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui libs
  bubble: ^1.1.9+1
  #font libs
  google_fonts: ^1.1.0

  #dependency injection
  get_it: ^4.0.1
  injectable: ^0.4.0

  #firebase related libs
  firebase_core: 0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_auth: ^0.16.0

  #bloc related libs
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1

  #code generator related libs
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  #code generator related libs
  build_runner: ^1.9.0
  freezed: ^0.10.8
  injectable_generator: ^0.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/

